CREATE TABLE IF NOT EXISTS CATALOG (ID INT PRIMARY KEY AUTO_INCREMENT,
	    NAME VARCHAR2(100) not null,
	    INN VARCHAR2(100) not null,
	    OGRN VARCHAR2(100) not null,
	    ADRESS VARCHAR2 (100)) not null;